---
name: Action

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'

jobs:
  Local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Runs local action
        uses: ./
      - name: Validates format of CSV file
        uses: blackstar257/docker-csvlint@master
        env:
          ACTION_STATE_NAME: "data.csv"
