---
name: Lint

on:
  pull_request:
    paths:
      - '*.md'
      - '*.py'
      - '*.y?ml'
      - 'Dockerfile'
  push:
    paths:
      - '*.md'
      - '*.py'
      - '*.y?ml'
      - 'Dockerfile'

jobs:
  Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: Dockerfile
  Markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: ".markdownlint.yml"
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: YAML check (yamllint)
        uses: ibiqlik/action-yamllint@master
        with:
          strict: true
